apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/artamim/SocialMediaInfra.git
    targetRevision: HEAD
    path: ClusterSetup
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
