apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: SuperStrongPass123!@#
  POSTGRES_DB: appdb

# This secret contains demonstration credentials for the PostgreSQL database. In a production environment, you should use more secure credentials and consider using a secret management solution to handle sensitive information. Also, ensure that the database credentials are not hardcoded in your application code and are accessed securely through environment variables or a secrets management tool.