apiVersion: v1
kind: Secret
metadata:
  name: appuser-secret
  namespace: default
type: Opaque
stringData:
  database_url: "postgresql+asyncpg://postgres:SuperStrongPass123%21%40%23@postgres:5432/appdb"