apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: SuperStrongPass123!@#
  POSTGRES_DB: appdb