apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-ebs
  annotations:
    argocd.argoproj.io/sync-wave: "1"
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  fsType: ext4
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer